<?php

########################################################################
# Extension Manager/Repository config file for ext: "libconnect"
#
# Auto generated by Extension Builder 2012-01-17
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'libconnect',
	'description' => 'tolle Extension',
	'category' => 'plugin',
	'author' => 'Torsten Witt',
	'author_email' => 'witt@sub.uni-hamburg.de',
	'author_company' => 'Stabi Hamburg',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>